### ISSUE TITLE
Fix Memory Leak within OpenCV

### ISSUE THREAD

**Issue by Byrdman32** [MissouriMRDT/Autonomy_Software#3]
Our current implementation of OpenCV has a memory leak whenever we use the `cv::Mat` object.

**Comment by ClayJay3** [comment]
Rebuilt OpenCV with CUDA, leak is still there and appears to happen as soon as opencv libs are included now.

**Comment by ClayJay3** [comment]
Seems that OpenCV just has memory leaks, they even provide suppression files for valgrind so that the leaks are ignored. Currently in the process of gathering .supp files and writing a script to run valgrind and deal with those.

According to the project contributors the leaks aren't important because they 'only happen once at the initialization of some classes' which means the program won't leak memory over time so it's still safe to use. That's a pretty dumb reasoning though as the OS will have to clean up the mess after the program exits and it also makes testing our project for leaks painful.

**Comment by ClayJay3** [comment]
Script has been written, .supp files will likely need to be added in the future as some functions aren't fully covered by OpenCV's supplied suppression file.
